@startuml ER Diagram
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity mobile_version{
    *_id: number
    --
    *isRequired: Boolean,
    *appId: string,
    *latestVersion: string,
    *createdAt: Date 
    *updatedAt: Date,
}

@enduml
