@startuml NavigationBarPanel Sequence Diagram

participant Client 
participant NavigationBarPanel
... ...
Client -> NavigationBarPanel : call component **<NavigationBarPanel />**
activate Client #D3D3D3
activate NavigationBarPanel #D3D3D3
    NavigationBarPanel -> NavigationBarPanel : Create a Appbar with app logo,\nmultiple menus , notification icon and profile icon
    NavigationBarPanel -> NavigationBarPanel : Whenever a new notification comes up for the loggined user \nis detect using **NotifictaionView** global state \nthe notification bell icon changes
    NavigationBarPanel -> userServices.ts : Request for loggined user deails 
    activate userServices.ts #D3D3D3
        userServices.ts -> User_Backend : Request for user details **`/users/:userId`**
        activate User_Backend #D3D3D3
            userServices.ts <-- User_Backend : return User
        deactivate User_Backend
        NavigationBarPanel <-- userServices.ts : return **User**
    deactivate userServices.ts 
    alt user details call successfull
        NavigationBarPanel -> NavigationBarPanel : Change profile icon with user's image using currentUserInfo state value
    else 
        NavigationBarPanel -> NavigationBarPanel : cannot change the Profile icon
    end
    NavigationBarPanel -> NavigationBarPanel : Bind the **renderHowDoiMenu**  
    NavigationBarPanel -> NavigationBarPanel : Bind the **renderEmployeeMenu**
    NavigationBarPanel -> NavigationBarPanel : Bind the **renderNotificationMenu**  
    NavigationBarPanel -> NavigationBarPanel : Bind the **renderRecruitmentMenu**
    NavigationBarPanel -> NavigationBarPanel : Bind the **renderProfileMenu**
    alt loggined user is "Hr Manager"
        NavigationBarPanel -> Client : User can receive expected App Bar with all menues
    else loggined user is "Manager"
        NavigationBarPanel -> Client : User can receive expected App Bar without **Admin** and **Recruitment** menu
    else loggined user is "Manager" and "Panel Member"
        NavigationBarPanel -> Client : User can receive expected App Bar without **Admin** menu
    else loggined user is "Team Member"
        NavigationBarPanel -> NavigationBarPanel : Change the **Team Memnber** menu with **My Performance**
        NavigationBarPanel -> Client : User can receive expected App Bar without **Admin** and **Recruitment** menu 
    end
deactivate Client
deactivate NavigationBarPanel

... ...
Client -> NavigationBarPanel : **renderHowDoiMenu**
activate Client #D3D3D3
activate NavigationBarPanel #D3D3D3
    NavigationBarPanel -> NavigationBarPanel : Call <HowDoIMenuPanel ...{props} />
    note right of NavigationBarPanel : props: {\n\tanchorEl={howDoIMenu}\n\tisShowMenu={isHowdoImenu}\n\tonClose={handleHowDoIMenuClose}\n\tuserRole={Currentuser's role}\n\tuserId={currentUser id!}\n}
    note right of NavigationBarPanel : Refer the how_do_i_menu_panel sequence diagram in how_do_i_menu_panel folder
    Client <-- NavigationBarPanel : return an JSX.element
deactivate Client
deactivate NavigationBarPanel

... ...
Client -> NavigationBarPanel : **renderEmployeeMenu**
activate Client #D3D3D3
activate NavigationBarPanel #D3D3D3
    NavigationBarPanel -> NavigationBarPanel : Call <TeamMemberMenuPanel ...{props} />
    note right of NavigationBarPanel : props: {\n\tanchorEl={employeeMenu}\n\tisShowMenu={isEmployeeMenu}\n\tonClose={handleHowEmployeeMenuClose}\n\tuserRole={Currentuser's role}\n\tuserId={currentUser id!}\n}
    note right of NavigationBarPanel : Refer the team_member_menu_panel sequence diagram in team_member_menu_panel folder
    Client <-- NavigationBarPanel : return an JSX.element
deactivate Client
deactivate NavigationBarPanel

... ...
Client -> NavigationBarPanel : **renderRecruitmentMenu**
activate Client #D3D3D3
activate NavigationBarPanel #D3D3D3
    alt current user is a Manager and also a panel member
        NavigationBarPanel -> NavigationBarPanel : Bind a Job menu options  
    else 
        NavigationBarPanel -> NavigationBarPanel : Bind a Job , Onboarding menu options
    end
    Client <-- NavigationBarPanel : return an JSX.element
deactivate Client
deactivate NavigationBarPanel

... ...
Client -> NavigationBarPanel : **renderProfileMenu**
activate Client #D3D3D3
activate NavigationBarPanel #D3D3D3
    NavigationBarPanel -> NavigationBarPanel : Bind menu with Two menu options, which is My Profile and Logout
    Client <-- NavigationBarPanel : return an JSX.element
deactivate Client
deactivate NavigationBarPanel

... ...
Client -> NavigationBarPanel : **renderNotificationMenu**
activate Client #D3D3D3
activate NavigationBarPanel #D3D3D3
    alt isNotificationLoading is true
        NavigationBarPanel -> NavigationBarPanel : Bind a Loader
    else fetched Notification empty  
        NavigationBarPanel -> NavigationBarPanel : Bind a text with empty indication
    else 
        NavigationBarPanel -> NavigationBarPanel : Bind the Notification detail as list
    end
    NavigationBarPanel -> NavigationBarPanel : Redirect to the **Hive application**
    Client <-- NavigationBarPanel : return an JSX.element
deactivate Client
deactivate NavigationBarPanel

... ...
... ...
...~~**Click Functionalities**~~...
... ...
Client -> NavigationBarPanel : User Click on the **Admin** menu
activate Client #D3D3D3
activate NavigationBarPanel #D3D3D3
    NavigationBarPanel -> NavigationBarPanel : Redirect to the `https://hive.avasoft.com/admin`
    Client <-- NavigationBarPanel : User can view the admin module form **Hive Application**
deactivate Client
deactivate NavigationBarPanel

... ...
Client -> NavigationBarPanel : User Click on the **Dashboard** menu
activate Client #D3D3D3
activate NavigationBarPanel #D3D3D3
    NavigationBarPanel -> NavigationBarPanel : Redirect to the `https://hive.avasoft.com/Overview`
    Client <-- NavigationBarPanel : User can view their dashboard on **Hive Application**
deactivate Client
deactivate NavigationBarPanel

... ...
Client -> NavigationBarPanel : User Click on the **Leave** menu
activate Client #D3D3D3
activate NavigationBarPanel #D3D3D3
    NavigationBarPanel -> NavigationBarPanel : Redirect to the `https://hive.avasoft.com/leavewfh`
    Client <-- NavigationBarPanel : User can view their leave requests on **Hive Application**
deactivate Client
deactivate NavigationBarPanel

... ...
Client -> NavigationBarPanel : User Click or Hover on the **Recruitment** menu
activate Client #D3D3D3
activate NavigationBarPanel #D3D3D3
    NavigationBarPanel -> NavigationBarPanel : call **recruitmentMenuOpen()** and \nit change the visibility of **renderRecruitmentMenu**, it opens the **Recruitemnt** menu \nand close all the other menu popups
    Client <-- NavigationBarPanel : User can view and select the options from **Recruitment** menu
deactivate Client
deactivate NavigationBarPanel

... ...
Client -> NavigationBarPanel : User Click or Hover on the **Team Member** or **My Performance** menu
activate Client #D3D3D3
activate NavigationBarPanel #D3D3D3
    NavigationBarPanel -> NavigationBarPanel : call **handleEmployeeMenuOpen()** and \nit change the visibility of **renderEmployeeMenu**, it opens the **Team Member** menu \nand close all the other menu popups
    Client <-- NavigationBarPanel : User can view and select the options from **Team Member** menu
deactivate Client
deactivate NavigationBarPanel

... ... 
Client -> NavigationBarPanel : User Click or Hover on the **How Do I?** menu
activate Client #D3D3D3
activate NavigationBarPanel #D3D3D3
    NavigationBarPanel -> NavigationBarPanel : call **handleHowDoIMenuOpen()** and \nit change the visibility of **renderHowDoiMenu**, it opens the **How Do I?** menu \nand close all the other menu popups
    Client <-- NavigationBarPanel : User can view and select the options from **How Do I?** menu
deactivate Client
deactivate NavigationBarPanel

... ... 
Client -> NavigationBarPanel : User Click or Hover on the **Profile Icon** menu
activate Client #D3D3D3
activate NavigationBarPanel #D3D3D3
    NavigationBarPanel -> NavigationBarPanel : call **handleProfileMenuOpen()** \nit change the visibility of **renderProfileMenu**, and it opens the **Profile** menu \nand close all the other menu popups
    Client <-- NavigationBarPanel : User can view and select the options from the menu
deactivate Client
deactivate NavigationBarPanel

... ... 
Client -> NavigationBarPanel : User Click on the **Notification Bell Icon** menu
activate Client #D3D3D3
activate NavigationBarPanel #D3D3D3
    NavigationBarPanel -> NavigationBarPanel : call **handleNotificationMenuOpen()** \nit change the visibility of **renderNotificationMenu**, and it Open the notiification menu with a loader by \nBy updating **isNotificationLoading** as true
    NavigationBarPanel -> userServices.ts : **fetchNotifications(userid)**
    activate userServices.ts #D3D3D3
        userServices.ts -> Hive_Backend : Request notifications details for the user\n **`/leave` in Post method with Payload**
        activate Hive_Backend #D3D3D3
            userServices.ts <-- Hive_Backend : return NotificationBO[]
        deactivate Hive_Backend 
        NavigationBarPanel <-- userServices.ts : return **NotificationBO[]**
    deactivate userServices.ts 
    NavigationBarPanel -> NavigationBarPanel : Update **isNotificationLoading** as false
    alt response NotificationBO[] is empty
        Client <-- NavigationBarPanel : User can view a popover with an indication text of that is empty
    else 
        Client <-- NavigationBarPanel : User can view the notifications for itself
    end
deactivate Client
deactivate NavigationBarPanel

... ...

Client -> NavigationBarPanel : When the user click the menuItems  
activate Client #D3D3D3
    activate NavigationBarPanel #D3D3D3
        alt case: When user Clicks the **Jobs** menuItem
            NavigationBarPanel -> NavigationBarPanel : user will be navigated\n to `https://hive.avasoft.com/recruitment`
        else case : When user Clicks the **Onboarding** menuItem
            NavigationBarPanel -> NavigationBarPanel : user will be navigated\n to `https://hive.avasoft.com/Onboarding`
        else case : When user Clicks the **My Profile** menuItem
            NavigationBarPanel -> NavigationBarPanel : user will be navigated\n to `https://hive.avasoft.com/profilecontainer?EmpId=${currentUserInfo.userId}&IsTeamMember=true`
        else case : When user Clicks the **Logout** menuItem
            NavigationBarPanel -> NavigationBarPanel : call **logoutFromHive()**
            activate NavigationBarPanel #D16587
                NavigationBarPanel -> NavigationBarPanel : clear the **sessionStorage**  
                NavigationBarPanel -> NavigationBarPanel : user will be navigated\n to `https://hive.avasoft.com`
            deactivate NavigationBarPanel
        end
        Client <-- NavigationBarPanel : user will be redirected to the respective page in Hive application
    deactivate NavigationBarPanel
deactivate Client


@enduml