@startuml UnAuthorizedUserPanel
participant Client
participant UnAuthorizedUserPanel

Client -> UnAuthorizedUserPanel : call the component **<UnAuthorizedUserPanel />**
activate Client #D3D3D3
activate UnAuthorizedUserPanel #D3D3D3

UnAuthorizedUserPanel -> UnAuthorizedUserPanel : Bind **Warning** text
UnAuthorizedUserPanel -> UnAuthorizedUserPanel : Bind **You are not Authorized to view this.** text
UnAuthorizedUserPanel -> UnAuthorizedUserPanel : Bind **Go to Dashboard** Button

note right of UnAuthorizedUserPanel: Refer button **onClick** function below in Click Functionalities

Client <-- UnAuthorizedUserPanel : \treturn the **view**
deactivate UnAuthorizedUserPanel
deactivate Client

... ...
... ...
... ...
...~~**Click Functionalities**~~...
... ...
... ...

Client -> UnAuthorizedUserPanel: **Go to Dashboard** Button \npressed
activate Client #D3D3D3
activate UnAuthorizedUserPanel #D3D3D3
UnAuthorizedUserPanel -> UnAuthorizedUserPanel : Navigate the user to **Dashboard** page
Client <-- UnAuthorizedUserPanel : \tNavigate the **user** to the dashboard page
deactivate UnAuthorizedUserPanel

deactivate Client

@enduml