@startuml UnAuthorizedUserPanel
participant Client
participant UnAuthorizedUserPanel

Client -> UnAuthorizedUserPanel : call the component **<UnAuthorizedUserPanel />**
activate Client #D3D3D3
activate UnAuthorizedUserPanel #D3D3D3

UnAuthorizedUserPanel -> UnAuthorizedUserPanel : Bind **Warning** text
UnAuthorizedUserPanel -> UnAuthorizedUserPanel : Bind **You are not Authorized to view this.** text
UnAuthorizedUserPanel -> UnAuthorizedUserPanel : Bind **Go to Dashboard** Button \n**Refer:** Button **onClick function** below

Client <-- UnAuthorizedUserPanel : \treturn the **view**
deactivate UnAuthorizedUserPanel
deactivate Client

... ...
... ...
note over Client: Click function
... ...

Client -> UnAuthorizedUserPanel: **Go to Dashboard** Button \n**onClick()** function pressed
activate Client #D3D3D3
activate UnAuthorizedUserPanel #D3D3D3
UnAuthorizedUserPanel -> UnAuthorizedUserPanel : Navigate the user to **Dashboard** page
Client <-- UnAuthorizedUserPanel : \treturn the **User** to the Dashboard page
deactivate UnAuthorizedUserPanel

deactivate Client

@enduml