@startuml UserCalendarPage

class UserInfo {
  userId\t\t : \tstring
  imageUrl\t\t : \tstring
  accessToken\t : \tstring
  reportings\t : \tstring[]
  role\t\t\t : \tstring
  employeeId\t : \tstring
}

class UserCalendarPage {
    formatAMPM\t\t\t\t : \tstring
    ..
    currentUserInfo\t\t\t : \tUserInfo
    ..
    nav\t\t\t\t\t\t : \tinstance of useNavigate
    ..
    userId\t\t\t\t\t : \tstring
    ..
    isLoading\t\t\t\t\t : \tboolean
    ..
    isAttendanceLoading\t\t : \tboolean
    ..
    visible\t\t\t\t\t : \tboolean
    ..
    childrenDrawer\t\t\t\t : \tboolean
    ..
    selectedDate\t\t\t\t : \tDate
    ..
    todoStatuses\t\t\t\t : \tTodoStatses[]
    ..
    todoTypes\t\t\t\t : \tTodoType[]
    ..
    currentTime\t\t\t\t : \tDate
    ..
    currentMonthTodos\t\t\t : \tTodoItem[]
    ..
    currentMonthAttendance\t\t : \tAttendanceItem[]
    ..
    currentPracticeId\t\t\t : \tstring
    ..
    tags\t\t\t\t\t\t : \tTagType[]
    ..
    highLightedDates\t\t\t : \tstring[]
    ..
    highlightedTagIds\t\t\t : \tstring[]
    ..
    searchParams\t\t\t\t : \tinstance of useSearchParams
    ..
    userName\t\t\t\t : \tstring
    ..
    userRole\t\t\t\t\t : \tstring
    ..
    statistics\t\t\t\t\t : \tany
    ..
    selectLocked\t\t\t\t : \tboolean
    ..
    attendanceValue\t\t\t : \tstring
    ..
    initialise()\t\t\t\t\t : \tvoid
    ..
    getStatistics()\t\t\t\t : \tvoid
    ..
    fetchTags()\t\t\t\t : \tvoid
    ..
    setUserDetails()\t\t\t : \tvoid
    ..
    setUpWithQueryString()\t\t : \tvoid
    ..
    setupUserCalander()\t\t : \tvoid
    ..
    showDrawer()\t\t\t\t : \tvoid
    ..
    getListData()\t\t\t\t : \t{type: string, content: string}[]
    ..
    getWorkingHours()\t\t\t : \tnumber[]
    ..
    isAllTasksCompleted()\t\t : \tboolean
    ..
    getAttendanceStatus()\t\t : \t[]
    ..
    menuTapped()\t\t\t\t : \tvoid
    ..
    generateMenu()\t\t\t : \tcomponent
    ..
    dateCellRender()\t\t\t : \tcomponent
    ..
    getPendingTodosCount()\t : \tnumber
    ..
    getViewingMonthTodo()\t\t : \tvoid
    ..
    getViewingPracticeId()\t\t : \tvoid
    ..
    getViewingMonthAttendance()\t : \tvoid
    ..
    onSelectedDateChange()\t : \tvoid
    ..
    dateHighlighted()\t\t\t : \tboolean
    ..
    isPastDate()\t\t\t\t : \tboolean
    ..
    getSelectedDateAttendance()\t : \tstring
}
@enduml