@startuml DayViewPanel

class DayViewPanel {
    days\t\t\t\t\t\t : \tstring[]
    ..
    accounts\t\t\t\t\t : \tuseMsal instance
    ..
    isLoading\t\t\t\t\t : \tboolean
    ..
    submittingChanges\t\t\t : \tboolean
    ..
    childrenDrawerMode\t\t : \tstring
    ..
    currentFocusingTodo\t\t : \tTodoItem
    ..
    highlightedTaskIds\t\t\t :  \tstring[]
    ..
    attendanceStatus\t\t\t :  \tstring
    ..
    nav\t\t\t\t\t\t :  \tuseNavigate instance
    ..
    getDayAttendance()\t\t\t : \tvoid
    ..
    onClose()\t\t\t\t\t : \tvoid
    ..
    showChildrenDrawer()\t\t : \tvoid
    ..
    onChildrenDrawerClose()\t : \tvoid
    ..
    getDayNameFromDate()\t\t : \tstring
    ..
    addNewTodo()\t\t\t\t : \tvoid
    ..
    deleteTodo()\t\t\t\t : \tvoid
    ..
    editTodo()\t\t\t\t : \tvoid
    ..
    viewTodo()\t\t\t\t : \tvoid
    ..
    editExistingTodo()\t\t\t : \tvoid
    ..
    getWorkHours()\t\t\t : \t{ etaHours: number, ataHours: number }
    ..
    antIcon\t\t\t\t\t : \tcomponent
    ..
    showAddNewTaskPanel()\t : \tvoid
    ..
    getComponent()\t\t\t : \tAddTodoPanel or EditTodoPanel component or null
}
@enduml