@startuml DayViewPanel
participant Client
participant DayViewPanel
participant attendance_service.ts
participant attendance_backend
participant todo_services.ts
participant todo_backend

Client -> DayViewPanel : call the component **<DayViewPanel {props}/>**
activate Client #D3D3D3
activate DayViewPanel #D3D3D3

note left of DayViewPanel:**Props:** \n\trefreshHandler\t\t\t : \tvoid \n\tuserId\t\t\t\t : \tstring \n\tcurrentPracticeId\t\t : \tstring \n\ttodos\t\t\t\t : \tTodoItem[] \n\tselectedDate\t\t\t : \tMoment \n\tvisible\t\t\t\t : \tboolean \n\tsetVisible\t\t\t\t : \tvoid \n\tchildrenDrawerVisible\t\t : \tboolean \n\tsetChildrenDrawerVisible\t : \tvoid \n\ttags\t\t\t\t\t : \tTagType[] or undefined \n\thighlightedTaskIds\t\t : \tstring[] \n\tisEditable\t\t\t\t : \tboolean \n\tattendanceStatus\t\t : \tstring

alt If the component mounted
    DayViewPanel -> DayViewPanel : Bind **Working status** of the user for the \nselected date by using the **getDayAttendance** \nmethod
    note right of DayViewPanel : Refer the **getDayAttendance** method below in Functions

    DayViewPanel -> DayViewPanel : Highlight the **Selected todos** whenever \nthe user opted for tag analytics use \n**highlightedTaskIds** to know whether the \nuser opted or not
end

DayViewPanel -> DayViewPanel : Bind **Selected calendar date**, \n**Working status**, \n**Todo statistics for selected date** \nby using the **DayStatsPanel** component
note right of DayViewPanel : Refer the **DayStatusPanel** in **day_stats_panel** \nfolder

DayViewPanel -> DayViewPanel : Bind **Total estimated work hours** \nfor the selected date by using the\n**getWorkHours** method
note right of DayViewPanel : Refer the **getWorkHours** method below in Functions

DayViewPanel -> DayViewPanel : Bind **Total Actual working hours** \nfor the selected date by using the\n**getWorkHours** method 
note right of DayViewPanel : Refer the **getWorkHours** method below in Functions

DayViewPanel -> DayViewPanel : Bind **Newly added task** or\n**Existing tasks** for the selected date by \nusing the **TodoViewPanel** component. \nBefore moving to next step first refer \nthe **TodoViewPanel** design and continue \nwith the methods **viewTodo**, **deleteTodo** \nand **editTodo** below
note right of DayViewPanel : Refer the **TodoViewPanel** in **todo_view_panel** \nfolder and methods below in Functions

DayViewPanel -> DayViewPanel : Show **Add Task Plus** button only on **current working day** \nand **previous working day** by using the **isEditable** \nvalue from props
note right of DayViewPanel : Refer **Add Task Plus** onclick function in below \nClick Functionalities

DayViewPanel -> DayViewPanel : Bind **AddTodoPanel** component to add the \ntask for the current working day or previous working \nday by statisfying the following condition
    alt If the user clicked the **Add Task Plus** button \nand the childrenDrawerMode is equal to "add"
        DayViewPanel -> DayViewPanel : call **getComponent** method to populate the \n**AddTodoPanel** component. Before moving \nto next step first refer the **AddTodoPanel** component \ndesign and continue with the method **addNewTodo**
        note right of DayViewPanel : Refer the **getComponent** and **addNewTodo** methods \nin Functions \nRefer the **AddTodoPanel** component in **add_todo_panel** \nfolder
    end

DayViewPanel -> DayViewPanel : Bind **EditTodoPanel** component to edit the \nexisting tasks for current working day or previous working \nday
    alt If the user clicked the **Edit** button \nand the childrenDrawerMode is \nequal to "edit"
        DayViewPanel -> DayViewPanel : call **getComponent** method to populate the \n**EditTodoPanel** component. Before moving \nto next step first refer the **EditTodoPanel** component \ndesign and continue with the method **editExistingTodo**
        note right of DayViewPanel : Refer the **getComponent** and **editExistingTodo** methods \nin Functions \nRefer the **EditTodoPanel** component in **edit_todo_panel** \nfolder
    end

DayViewPanel -> DayViewPanel : Bind **EditTodoPanel** component to view the \nexisting tasks for all the days
    alt If the user clicked the **view** button \nand the childrenDrawerMode is \nequal to "view"
        DayViewPanel -> DayViewPanel : call **getComponent** method to populate the \n**EditTodoPanel** component
        note right of DayViewPanel : Refer the **getComponent** in Functions \nRefer the **EditTodoPanel** component in **edit_todo_panel** \nfolder
    end

note right of DayViewPanel : Refer the **Day view Panel** close functionality in Click Functionalities

Client <-- DayViewPanel : \treturn the appropriate **view**
deactivate DayViewPanel
deactivate Client

... ...
... ...
... ...
...~~**Functions**~~...
... ...
... ...

Client -> DayViewPanel: **getDayAttendance**
activate Client #D3D3D3
activate DayViewPanel #D3D3D3

DayViewPanel -> attendance_service.ts: call the **getAttendance** method in \nattendance services file 
    activate attendance_service.ts #D3D3D3
    attendance_service.ts -> attendance_backend: call **Base URL/attendance?** \n**userId=${userId}&date=${parsedDate}**
    activate attendance_backend #D3D3D3
    attendance_backend -> attendance_backend: get the **working status** of the \nuser for the specific date
    attendance_backend --> attendance_service.ts: return attendance details
    deactivate attendance_backend
    attendance_service.ts --> DayViewPanel: return attendance details
    deactivate attendance_service.ts
    DayViewPanel -> DayViewPanel: set the reponse to the varibale **attendanceStatus**
DayViewPanel --> Client: **render** the entire component

deactivate DayViewPanel
deactivate Client
... ...

Client -> DayViewPanel: **getWorkHours**
activate Client #D3D3D3
activate DayViewPanel #D3D3D3
    DayViewPanel -> DayViewPanel: calculate the total eta and ata by using the todos from props 
    DayViewPanel --> Client: return object with total eta and ata
    deactivate DayViewPanel
deactivate Client
... ...

Client -> DayViewPanel: **showChildrenDrawer**
activate Client #D3D3D3
activate DayViewPanel #D3D3D3
    DayViewPanel -> DayViewPanel: Whenever the user opens the \n**Add or Edit or View todo panel** drawer \nthen call the **setChildrenDrawerVisible** function \nfrom props and pass the parameter as **true** 
    DayViewPanel --> Client: opens appropriate drawer component
    deactivate DayViewPanel
deactivate Client
... ...

Client -> DayViewPanel: call **getComponent**
activate Client #D3D3D3
activate DayViewPanel #D3D3D3
    alt If the value of the **childrenDrawerMode** is **"add"**
        DayViewPanel -> Client: This method returns the **AddTodoPanel**
    end

    alt if the value of the **childrenDrawerMode** \nis **"edit"** or **"view"**
        DayViewPanel -> Client: This method returns **EditTodoPanel** component
    end

    alt If not matched with any of the above options
        DayViewPanel -> Client: return **null** tag
        deactivate DayViewPanel
    end    
deactivate Client
... ...

Client -> DayViewPanel: call **addNewTodo**
activate Client #D3D3D3
activate DayViewPanel #D3D3D3
    DayViewPanel -> DayViewPanel: When the user filled the task details and clicked the add \ntodo button, enable the loader by assign the **submittingChanges** \nvariable value to **true** and
    DayViewPanel -> todo_services.ts: call the **addTodo(userId, todo, todoDate)**
    activate todo_services.ts #D3D3D3
    todo_services.ts -> todo_backend: call **Base URL/todos?userId=$**\n**{userId}&date=${todoDate}**
    activate todo_backend #D3D3D3
    todo_backend -> todo_backend: creates a new todo
    todo_backend --> todo_services.ts: return response
    deactivate todo_backend
    todo_services.ts --> DayViewPanel: return response
    deactivate todo_services.ts

    DayViewPanel -> DayViewPanel: Disable the loader after getting a \nresponse whether it is success or fail. \nTo disable it set **submittingChanges** \nvariable to **false**

    alt If the response status code is 200
        DayViewPanel -> DayViewPanel: check if **"add"** or \n**"add_and_continue"** button is clicked by the user
    end
    
    alt If user has clicked the **"add" button**
        DayViewPanel -> DayViewPanel: close the **Add todo panel** drawer and refresh \nthe page. To close the drawer call **onChildrenDrawerClose** \nmethod and to refresh trigger the **refreshHandler** method from \nprops
        note right of DayViewPanel: Refer **onChildrenDrawerClose** method in Click Functionalities
    end
    
    alt If user has clicked the **"add_and_continue"** button
        DayViewPanel -> DayViewPanel: clear all the fields and allow the user to continue with the \nadd task drawer without closing it. To do that set \n**childrenDrawerMode** variable to **"add"**
    end
    DayViewPanel --> Client: New todo will be added
    deactivate DayViewPanel
deactivate Client
... ...

Client -> DayViewPanel: call **getDayNameFromDate**
activate Client #D3D3D3
activate DayViewPanel #D3D3D3
    DayViewPanel -> DayViewPanel: Extracts the day's name from the given date
    DayViewPanel --> Client: return string
    deactivate DayViewPanel
deactivate Client
... ...

Client -> DayViewPanel: call **editExistingTodo**
activate Client #D3D3D3
activate DayViewPanel #D3D3D3
    DayViewPanel -> DayViewPanel: When the user has **modified** the **task** details and clicked the **edit todo** \nbutton, check the user has filled the **working status** or **not**

    alt If filled
        DayViewPanel -> DayViewPanel: enable the loader by assign the **submittingChanges** \nvariable value to **true**
        DayViewPanel -> todo_services.ts: call the **editTodoById(userId, todo, move)**
        activate todo_services.ts #D3D3D3
        todo_services.ts -> todo_backend: call **Base URL/todos/${todo._id}\n?userId=${userId}**
        activate todo_backend #D3D3D3
        todo_backend -> todo_backend: Edit the existing todo for \nthe given id
        todo_backend --> todo_services.ts: return response
        deactivate todo_backend
        todo_services.ts --> DayViewPanel: return response
        deactivate todo_services.ts

        DayViewPanel -> DayViewPanel: Disable the loader after getting a response whether it is success \nor fail. To disable it set **submittingChanges** variable to \n**false**
        DayViewPanel -> DayViewPanel: close the **Edit todo panel** drawer and refresh \nthe page. To close the drawer call \n**onChildrenDrawerClose** method and to refresh, trigger the \n**refreshHandler** method from props
        note right of DayViewPanel: Refer **onChildrenDrawerClose** method in Click Functionalities

        DayViewPanel --> Client: Existing todo will be updated
        deactivate DayViewPanel
    end
deactivate Client
... ...

... ...
... ...
...~~**Click Functionalities**~~...
... ...
... ...

Client -> DayViewPanel: When **Add Task Plus** button clicked \nby the user, call **showAddNewTaskPanel**
activate Client #D3D3D3
activate DayViewPanel #D3D3D3
    alt If the user has filled the working status
        DayViewPanel -> DayViewPanel: open the **add todo panel**. To do that first set \n**childrenDrawerMode** variable value to **"add"** and \ncall the **showChildrenDrawer** method
        note right of DayViewPanel: Refer the **showChildrenDrawer** method in Functions
        DayViewPanel --> Client: It will open the add todo panel
    end

    alt If the user has not filled the working status
        DayViewPanel -> DayViewPanel: prompt the message **"Please fill your attendance"**
        DayViewPanel --> Client: Promp error message to the user
        deactivate DayViewPanel
    end
deactivate Client
... ...


Client -> DayViewPanel: on day view panel drawer closed trigger **onClose**
activate Client #D3D3D3
activate DayViewPanel #D3D3D3
    DayViewPanel -> DayViewPanel: Whenever the user closed the \n**Day view panel** drawer or page \ngot refreshed then set the variable \n**visible** to **false** and variable **isLoading** to **true** 
    DayViewPanel --> Client: return closes the day view panel \ndrawer
    deactivate DayViewPanel
deactivate Client
... ...

Client -> DayViewPanel: call **onChildrenDrawerClose**
activate Client #D3D3D3
activate DayViewPanel #D3D3D3
    DayViewPanel -> DayViewPanel: Whenever the user closes the \n**Add or Edit or View todo panel** drawer \nthen call the **setChildrenDrawerVisible** function \nfrom props and pass the parameter as **false** 
    DayViewPanel --> Client: opens appropriate drawer component
    deactivate DayViewPanel
deactivate Client
... ...

Client -> DayViewPanel: When the user clicked the edit \ntodo button, call **editTodo**
activate Client #D3D3D3
activate DayViewPanel #D3D3D3    
    alt If the user has filled the \nworking status
        DayViewPanel -> DayViewPanel: open the **edit todo panel**. To do that first \nset **childrenDrawerMode** variable value to \n**"edit"** and call the **showChildrenDrawer** \nmethod and set the appropriate todo details \nin **currentFocusingTodo** variable.
        DayViewPanel --> Client: opens the Edit Todo Panel 
        note right of DayViewPanel: Refer **showChildrenDrawer** method in Functions
    end
    
    alt If the user has not filled the \nworking status
        DayViewPanel -> DayViewPanel: prompt the message **"Please fill your attendance"**
        DayViewPanel --> Client: prompt the error message
        deactivate DayViewPanel
    end

    
deactivate Client
... ...

Client -> DayViewPanel: When the user clicked the **view todo** \nbutton call **viewTodo**
activate Client #D3D3D3
activate DayViewPanel #D3D3D3
    alt If the user has filled the \nworking status
        DayViewPanel -> DayViewPanel: open the **edit todo panel**. To do that first \nset **childrenDrawerMode** variable value to \n**"view"** and call the **showChildrenDrawer** \nmethod
        DayViewPanel --> Client: opens the Edit Todo Panel \nto view the task
        note right of DayViewPanel: Refer **showChildrenDrawer** method in Functions
    end
    
    alt If the user has not filled the \nworking status
        DayViewPanel -> DayViewPanel: prompt the message **"Please fill your attendance"**
        DayViewPanel --> Client: prompt the error message
        deactivate DayViewPanel
    end
deactivate Client
... ...

Client -> DayViewPanel: When the user clicked the **delete todo** \nbutton call **deleteTodo**
activate Client #D3D3D3
activate DayViewPanel #D3D3D3

    alt If the user has filled the \nworking status
        DayViewPanel -> DayViewPanel: prompt the delete confirmation popup

        alt If user confirmed the delete prompt
            DayViewPanel -> DayViewPanel: enable the loader by assign the \n**submittingChanges** variable value \nto **true** and
            
            DayViewPanel -> todo_services.ts: call the **deleteTodoById(userId, todoId)**
            activate todo_services.ts #D3D3D3
            todo_services.ts -> todo_backend: call **Base URL/todos/${todoId}?userId=${userId}**
            activate todo_backend #D3D3D3
            todo_backend -> todo_backend: Delete the todo for \nthe given id
            todo_backend --> todo_services.ts: return response
            deactivate todo_backend
            todo_services.ts --> DayViewPanel: return response
            deactivate todo_services.ts

            DayViewPanel -> DayViewPanel: Disable the loader after getting a response whether it is success \nor fail. To disable it set **submittingChanges** variable to \n**false**
            DayViewPanel -> DayViewPanel: close the **Delete confirmation popup** and \nrefresh the page. To refresh trigger the **refreshHandler** method \nfrom props
        end

        DayViewPanel --> Client: remove the todo which \nuser has selected
    end
    
    alt If the user has not filled the \nworking status
        DayViewPanel -> DayViewPanel: prompt the message **"Please fill your attendance"**
        DayViewPanel --> Client: prompt the error message
        deactivate DayViewPanel
    end
deactivate Client
... ...

@enduml