@startuml find_practice_manager
participant Client #64D1AF
participant microsoftUser.service.ts
participant DB #FFC0CB

Client -> microsoftUser.service.ts : findDirectManager( managerId: string)
activate Client #D3D3D3
    activate microsoftUser.service.ts #D3D3D3
        microsoftUser.service.ts -> DB : microsoftUsersSchema.findOne({ userId: managerId });
        activate DB #D3D3D3
            microsoftUser.service.ts <-- DB : MicrosoftUser
        deactivate DB
        microsoftUser.service.ts -> microsoftUser.service.ts : get the return response\n save that in a variable\n called **result**
        Client <-- microsoftUser.service.ts : result
    deactivate microsoftUser.service.ts
deactivate Client
@enduml