@startuml getReporteeDetails method
participant Consumer #64D1AF
participant microsoftUser.service.ts
participant DB #FFC0CB

activate Consumer #D3D3D3
activate microsoftUser.service.ts #D3D3D3
 
Consumer -> microsoftUser.service.ts : request **MicrosodtUser[]** for particluar userIds\n **getReporteeDetails(userIds)**

microsoftUser.service.ts -> DB : decalre a variable **response** and request DB for MicrosoftUser details

activate DB #D3D3D3
DB -> DB : microsoftUsersSchema.find({\n\tuserId: { $in: reporteesId },\n})

microsoftUser.service.ts <-- DB : return **MicrosoftUser[]**

deactivate DB

Consumer <-- microsoftUser.service.ts : return **response** as **MicrosoftUser[]**
deactivate microsoftUser.service.ts
deactivate Consumer
@enduml
