@startuml GraphUserTile
participant Client
participant GraphUserTile

Client -> GraphUserTile : call the component **<GraphUserTile {props}/>**
activate Client #D3D3D3
activate GraphUserTile #D3D3D3

note left of GraphUserTile:**Props:** \n\tuserId: string, \n\tname: string, \n\tposition: string, \n\tattendence: string, \n\ttodos: GraphTodo[] | [], \n\tonViewAllClicked: Function, \n\tonViewBranchingClicked: Function, \n\treportings: number

GraphUserTile -> GraphUserTile : Bind **User Profile Picture** by \nusing the component **ImageAvatar** \nand the **userId** from the props
note right of GraphUserTile : Refer image_avatar component sequence diagram in component/image_avatar folder
GraphUserTile -> GraphUserTile : Bind **User Name** by using \nthe **name** from props
GraphUserTile -> GraphUserTile : Bind **Role** by using \nthe **position** from props
GraphUserTile -> GraphUserTile : Bind user attendance status \n**icon** by calling the method \n**getWorkingStatusIcon()**
note right of GraphUserTile : Refer the method below

alt When todos length is greater than 0
    GraphUserTile -> GraphUserTile : Loop and bind the **Todos** \nby using the **GraphTodoListPanel** \ncomponent
    note right of GraphUserTile : Refer graph_todo_list_panel component sequence diagram in component/graph_todo_list_panel folder
end

alt When todos length is not greater than 0
    GraphUserTile -> GraphUserTile : Bind **No Todos Found**
end

GraphUserTile -> GraphUserTile : Bind **View All** and **View Reportings** \nbuttons when the users has \nreportees. When the user has no \nreportees then bind only **View All** \nbutton. \n**Note:** Use **reportings** from props \nto know whether user has reportings or not\n
GraphUserTile -> GraphUserTile : When **View All** clicked trigger \n**onViewAllClicked()** function from props
GraphUserTile -> GraphUserTile : When **View Reportings** clicked trigger \n**onViewBranchingClicked()** function from \nprops


Client <-- GraphUserTile : \treturn the appropriate **view**
deactivate GraphUserTile
deactivate Client

... ...
... ...
...~~**Click functionalities**~~...
... ...

Client -> GraphUserTile: call **getWorkingStatusIcon**
activate Client #D3D3D3
activate GraphUserTile #D3D3D3

    alt if attendance value from props \nis equal to "Working" or "On Duty" \nor "On Site"
        GraphUserTile --> Client : return **Working** icon as \ntype react component
    end

    alt if attendance value from props \nis equal to "WFH"
        GraphUserTile --> Client : return **WFH** icon as \ntype react component
    end

    alt if attendance value from props \nis equal to "Comp Off" or \nincludes the term "Leave"
        GraphUserTile --> Client : return **Leave** icon as \ntype react component
    end

    alt if attendance value from props \nis null
        GraphUserTile --> Client : return an empty element
        deactivate GraphUserTile
    end

deactivate Client

@enduml