@startuml ER Diagram
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity attendance{
    *_id: number
    --
    *microsoftUserId: string,
    *attendance_status: string,
    *date: Date,
    *createdAt: Date 
    *updatedAt: Date,
}

@enduml
