@startuml ER Diagram
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity leader_ships{
    *_id: number
    --
    *microsoftUserId: string,
    *name: string,
    *domain: string,
    *mail: string,
    *hrpoc: string,
    *hrmail: string,
}

@enduml
