@startuml ER Diagram
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity microsoft_users{
    *_id: number
    --
    *userId: string,
    *name: string,
    *role: string,
    *practice: string,
    *mail: string,
    *employeeId: string,
    *reportings: string,
    *last_access: Date,
    *managerId: string,
    *isAdmin: Boolean,
}

@enduml