@startuml ER Diagram
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity tags{
    *_id: number
    --
    *microsoftUserId: string,
    *tagName: string,
    *type: string,
    *createdAt: Date 
    *updatedAt: Date,
}

@enduml
