@startuml AddTodoPanel

class AddTodoPanel {
    todoType\t\t\t : \tstring
    ..
    tag\t\t\t\t : \tstring[]
    ..
    datePickerVisibility\t : \tboolean
    ..
    dates\t\t\t : \tDate[]
    ..
    form\t\t\t\t : \tform instance
    ..
    formActionType\t : \t"add" or "add_and_continue"
    ..
    regex\t\t\t : \tstring
    ..
    onFinish()\t\t : \tvoid
    ..
    onFinishFailed()\t : \tvoid
    ..
    onTagSelected()\t : \tvoid
    ..
    handleCheckBox()\t : \tvoid
}
@enduml