@startuml AddTodoPanel
participant Client
participant AddTodoPanel

Client -> AddTodoPanel : call the component **<AddTodoPanel {props}/>**
activate Client #D3D3D3
activate AddTodoPanel #D3D3D3

note left of AddTodoPanel:**Props:** \n\tsubmittingChanges: boolean, \n\tuserId: string, \n\tsubmitChanges: void, \n\ttags: TagType[] | undefined

AddTodoPanel -> AddTodoPanel : Bind **Text fields** to add title and \nestimated effort of the task.
AddTodoPanel -> AddTodoPanel : Bind **Text area** to add the comments \nof the task
AddTodoPanel -> AddTodoPanel : Bind **Dropdown** to choose the tags \nof the task
AddTodoPanel -> AddTodoPanel : Bind **Radio button** to choose the type \nof the task
AddTodoPanel -> AddTodoPanel : Bind **Checkbox** so that the user \ncan add recurring tasks 
note right of AddTodoPanel : Refer checkbox **onChange** \nfunctionality below
AddTodoPanel -> AddTodoPanel : When the user checked the **"repeat the task"** \ncheckbox, Show **Multiple date picker** \ndropdown to add recurring task
AddTodoPanel -> AddTodoPanel : Bind **Add Task Button** to add the task
AddTodoPanel -> AddTodoPanel : Bind **Add Task & Continue Button** to \nadd task and to continue with the next \ntask

Client <-- AddTodoPanel : \treturn the appropriate **view**
deactivate AddTodoPanel
deactivate Client

... ...

... ...

Client -> AddTodoPanel : entering value on title field
activate Client #D3D3D3
activate AddTodoPanel #D3D3D3

alt If the entered title is empty
    AddTodoPanel -> Client : User can view an \nerror message **"Please enter a title!"** below the field
end

alt If the entered title's length \nis less than 3
    AddTodoPanel -> Client : User can view an \nerror message **"Title should not** \n**be less than 3 characters."** below the field
end

alt if the title is not matched \nwith the following /[a-zA-Z]/ \nregex condition
    AddTodoPanel -> Client : User can view an \nerror message **"Title should have** \n**atleast one alphabetic character."** below the field
end

deactivate AddTodoPanel
deactivate Client

... ...

... ...

Client -> AddTodoPanel : entering values to estimated effort field
activate Client #D3D3D3
activate AddTodoPanel #D3D3D3

alt If the entered estimated effort is empty
    AddTodoPanel -> Client : User can view an error message **"Please enter the** \n**Estimated Effort of this work!"** below the field
end

alt If the entered estimated effort is not a number
    AddTodoPanel -> Client : User can view an error message **"Enter a valid** \n**effort (should be a number)"** below the field 
end

alt If the entered estimated effort is greater than 8
    AddTodoPanel -> Client : User can view an error message **"Please split your** \n**works into Subtasks!"** below the field 
end

alt If the entered estimated effort is lesser than 0 
    AddTodoPanel -> Client : User can view an error message **"Please enter valid Estimated** \n**Effort for this task!"** below the field
end
deactivate AddTodoPanel
deactivate Client

... ...

... ...

Client -> AddTodoPanel : entering values to addtional notes field
activate Client #D3D3D3
activate AddTodoPanel #D3D3D3

alt if the comments is not matched \nwith the following /[a-zA-Z]/ \nregex condition
    AddTodoPanel -> Client : User can view an error message of \n**"Title should have atleast one alphabetic character."**  below the field
end

deactivate AddTodoPanel
deactivate Client

... ...

... ...

Client -> AddTodoPanel : when the user has choosed any tag
activate Client #D3D3D3
activate AddTodoPanel #D3D3D3

AddTodoPanel -> AddTodoPanel: trigger the **onTagSelected** method\nset the selected value to the \nvariable **tag** to update the \ntag dropdown with the selected value

alt If the user has not choosed \nany one of the default tag
    AddTodoPanel -> Client : throw an error message and user can view \n**"Please choose atleast one default tag"**  error below the field
end

alt If the user has choosed more than one \ndefault tag
    AddTodoPanel -> Client : throw an error message and user can view \n**"Please select only one default tag"** error below the field
end

deactivate AddTodoPanel
deactivate Client

... ...

... ...

Client -> AddTodoPanel : when the user has choosed \nany **task type**
activate Client #D3D3D3
activate AddTodoPanel #D3D3D3

AddTodoPanel -> AddTodoPanel : set the selected todo type to the \nvariable **todoType** to update the \nselected value radio button
AddTodoPanel --> Client: User can view the selection

deactivate AddTodoPanel
deactivate Client

... ...

... ...

Client -> AddTodoPanel : when the user has clicked the repeat \nthis task **checkbox**
activate Client #D3D3D3
activate AddTodoPanel #D3D3D3
    AddTodoPanel -> AddTodoPanel : trigger **handleCheckBox** method
    activate AddTodoPanel #D16587
        alt If the user has checked the checkbox
            AddTodoPanel -> AddTodoPanel : set **true** to variable **datePickerVisibility** \nto display the multiple date picker \ndropdown to the user
            Client <-- AddTodoPanel : User can able to view a select input with date picker
        end

        alt If the user has un checked the checkbox
            AddTodoPanel -> AddTodoPanel : set **false** to variable **datePickerVisibility** \nto hide the multiple date picker
            Client <-- AddTodoPanel : User can view the select input hiding
        end
    deactivate AddTodoPanel
deactivate AddTodoPanel
deactivate Client

... ...

... ...

Client -> AddTodoPanel : when the user has selected multiple dates
activate Client #D3D3D3
activate AddTodoPanel #D3D3D3

AddTodoPanel -> AddTodoPanel : set the selected dates to the \nvariable **dates** to update the \nmultiple date picker dropdown
AddTodoPanel --> Client: User can view the multiple dates which selected in the field

deactivate AddTodoPanel
deactivate Client

... ...

... ...

Client -> AddTodoPanel : when the user has clicked the \n**Add Task** button
activate Client #D3D3D3
activate AddTodoPanel #D3D3D3

AddTodoPanel -> AddTodoPanel : set the variable **formActionType** to \n"add" and submit the form by triggering \nthe method **onFinish** after satisfying \nall the above validations
AddTodoPanel --> Client: **onFinish** method in parent will trigger and send entered values to parent \nParent can get the entered field values

deactivate AddTodoPanel
deactivate Client

... ...

... ...

Client -> AddTodoPanel : when the user has clicked the \n**Add Task & Continue** button
activate Client #D3D3D3
activate AddTodoPanel #D3D3D3

AddTodoPanel -> AddTodoPanel : set the variable **formActionType** to \n"add_and_continue" and submit the \nform by triggering the method **onFinish** \nafter satisfying all the above validations \nand clear all the fields. Setting the variable \n"add_and_continue" will never close the \n**Add Todo Panel** drawer so the user can \nanother task
AddTodoPanel --> Client: **onFinish** method in parent will trigger and send entered values to parent\nParent can get the entered field values

deactivate AddTodoPanel
deactivate Client
@enduml